#:schema https://hexdoc.hexxy.media/schema/core/Properties.json
modid = "hexal"
book = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "remaint"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    "{_fabric.src}/main/resources",
    { path="{^_fabric.src}/generated/resources", required=false },
    "{_forge.src}/main/resources",
    { path="{^_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hexal/_export/generated"

[template]
icon = "icon.png"
include = [
    "hexal",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hexal"
author = "vgskye"
show_landing_text = false

[textures]
strict = false
missing = [
    "minecraft:chest",
]

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }
_per_world_value = "true"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/common/lib/hex/HexalActions.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_fabric.package}/FabricHexalInitializer.kt"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../Common/src"
package = "{src}/main/java/ram/talia/hexal"

[_fabric]
src = "../Fabric/src"
package = "{src}/main/java/ram/talia/hexal/fabric"

[_forge]
src = "../Forge/src"
package = "{src}/main/java/ram/talia/hexal/forge"
